[news]
title = "어피티 ─ 뉴스"
url = "https://uppity.co.kr/news"
entrySelector = "ul.li_body.holder"
titleSelector = "a.list_text_title._fade_link span"
linkSelector = "a.list_text_title._fade_link"
contentSelector = "li.category.hidden-xs a._fade_link em"
waitUntil = "networkidle"

[serial]
title = "어피티 ─ 시리얼"
url = "https://uppity.co.kr/serial"
entrySelector = "div._post_row.post_row.tabled div.list-style-card.table-cell._card_wrap:nth-child(n+2)"
titleSelector = "div.title.title-block"
linkSelector = "a"
contentSelector = "div.title.title-block span"
imageSelector = "div.card_wrapper"
waitUntil = "networkidle"

[moneylog]
title = "어피티 ─ 머니로그"
url = "https://uppity.co.kr/moneylog"
entrySelector = "div._post_row.post_row.tabled div.list-style-card.table-cell._card_wrap"
titleSelector = "div.title.title-block"
linkSelector = "a.post_link_wrap._fade_link"
contentSelector = "div.title.title-block span"
imageSelector = "div.card_wrapper"
waitUntil = "networkidle"

[moneyletter_archive]
title = "어피티 ─ 머니레터"
url = "https://uppity.co.kr/moneyletter_archive"
entrySelector = "ul.li_body.holder"
titleSelector = "li.tit a.list_text_title._fade_link span"
linkSelector = "li.tit a.list_text_title._fade_link"
contentSelector = "li.name"
waitUntil = "networkidle"